# GiDi WEB → NIXPACKS_CONFIG_FILE=nixpacks.web.toml

[phases.install]
cmds = ["NODE_ENV=development pnpm install --frozen-lockfile"]

[phases.build]
dependsOn = ["install"]
cmds = ["pnpm run build:web", "test -d apps/web/.next"]

[start]
cmd = "pnpm --filter web start"
